[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chest-cancer-net"
version = "0.1.0"
description = "Chest cancer classification system (FastAPI + Streamlit)"
requires-python = ">=3.12"
