artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/166i44CxICqxH3bmvXpKUNy8ciLqVUeZr/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  dataset_dir: artifacts/data_ingestion/Chest-CT-Scan-data
  train_dir: artifacts/data_ingestion/Chest-CT-Scan-data/train
  val_dir: artifacts/data_ingestion/Chest-CT-Scan-data/val
  test_dir: artifacts/data_ingestion/Chest-CT-Scan-data/test

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pt
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.pt

hyperparameter_tuning:
  enabled: true        
  n_trials: 30
  max_epochs: 10
  direction: minimize
  study_name: resnet18_optuna
  batch_size_choices: [4, 8, 16, 32]


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.pt
